server:
  servlet:
    context-path: /api/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delta_trade?charset=utf8mb4
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  mail:
    host: smtp.163.com
    protocol: smtp
    username: Ray7heo@163.com
    password: LDFPCJYQOGNEIMWN
    properties:
      from: Ray7heo@163.com
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  profiles:
    active: dev
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: 1
      logic-not-delete-value: 0